- hosts: ssh_windows
  gather_facts: no
  tasks:
    - name: Restart WMI
      win_shell: |
        Restart-Service -Name Winmgmt -Force
      register: result_get_host

    - name: display result_get_host
      debug:
        var: result_get_host
